name: create interview folder on _metadata.csv upload
on:
  push:
    paths:
      - 'interviews/*.csv'

jobs:
  process_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create interview folder, move csv, and delete original upload
        run: |
          for filepath in interviews/*_metadata.csv; do
            [ -f "$filepath" ] || continue
            filename=$(basename "$filepath" .csv)
            foldername="${filename/_metadata/}"
            target_dir="interviews/${filename}"
            
            # Create interview folder
            mkdir -p "$target_dir"
            mv "$filepath" "$target_dir/${filename}.csv"

            # Move the csv into the new folder
            mv "$filepath" "$target_dir/${filename}.csv"
            
          done

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add interviews/
          git commit -m "create interview folder from _metadata.csv upload" || echo "No changes to commit"
          git push

